version: '2'
services:
  git: 
    build: ./dockerfiles/git
    ports:
     - "10022:22"
    volumes:
     - ./volumes/git:/git/
    
  jenkins_master:
    image: jenkins:latest
    ports:
     - "8080:8080"
     - "50000:50000"
    volumes:
     - ./volumes/jenkins:/var/jenkins_home

   
  sonarqube:
    image: sonarqube:latest
    ports:
     - "9000:9000"
     - "9092:9092"
  nexus:
    image: sonatype/nexus:latest
    ports:
     - "8081:8081"
  
  
  selenium_hub:
    image: selenium/hub:latest
    ports:
     - "4444:4444"
     - "5555:5555"
    environment:
     - GRID_TIMEOUT=10000
  selenium_node_firefox:
    image: selenium/node-firefox:latest
    environment:
     - HUB_PORT_4444_TCP_ADDR=selenium_hub
     - HUB_PORT_4444_TCP_PORT=4444
  selenium_node_chrome:
    image: selenium/node-chrome:latest
    environment:
     - HUB_PORT_4444_TCP_ADDR=selenium_hub
     - HUB_PORT_4444_TCP_PORT=4444
   
  docker_controller: 
    build: ./dockerfiles/docker_controller
    ports:
     - "10023:22"
   

  
    