version: '2'
services:
  git: 
    build: ./dockerfiles/git
    ports:
     - "10022:22"
    
  jenkins_master:
    image: kornzysiek/jenkins
    ports:
     - "8080:8080"
     - "50000:50000"

  sonarqube:
    image: sonarqube:latest
    ports:
     - "9000:9000"
     - "9092:9092"

  nexus:
    image: sonatype/nexus:latest
    ports:
     - "8081:8081" 
   
  zalenium:
    build: ./dockerfiles/zalenium
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - ./videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
            
    ports:
      - 4444:4444
    command:
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 800 --screenHeight 600
            --timeZone "Europe/Berlin"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
  
  docker_controller: 
    build: ./dockerfiles/docker_controller
    ports:
     - "10023:22"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock 
 

  
    
